name: immich

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    ports:
      - "2283:2283"
      - "3001:3001"  # backend API for CLI
    volumes:
      - /share/ZFS21_DATA/immich/upload:/usr/src/app/upload
      - /share/ZFS21_DATA/immich/upload/library:/external/onedrive:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - immich-net

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich_machine_learning
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    networks:
      - immich-net

  redis:
    image: docker.io/valkey/valkey:8-bookworm
    container_name: immich_redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    networks:
      - immich-net

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich_postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: HDD
    volumes:
      - /share/ZFS20_DATA/immich-dbdata:/var/lib/postgresql/data
    restart: always
    networks:
      - immich-net

volumes:
  model-cache:

networks:
  immich-net:
    driver: bridge
