version: "3.8"

name: immich

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    ports:
      - "2283:2283"  # CLI
      - "3001:3001"  # API
    volumes:
      - /share/ZFS21_DATA/immich/upload:/usr/src/app/upload
      - /share/ZFS21_DATA/immich/upload/library:/external/onedrive:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - database
      - redis
    restart: always
    networks:
      - immich-net

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich_machine_learning
    restart: always
    networks:
      - immich-net

  redis:
    image: docker.io/valkey/valkey:8-bookworm
    container_name: immich_redis
    restart: always
    networks:
      - immich-net

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: database
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - immich_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - immich-net

volumes:
  immich_pgdata:

networks:
  immich-net:
